export type Site = {
  name: string
  description: string | null
  country: string
  version: 'original' | 'english'
  url: string
  enabled: boolean
}

export function siteSlug(site: Site): string {
  const base = site.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g,
      '-')
    .replace(/^-|-$/g,
      '')
  return site.version === 'english' ? `${base}-english` : base
}

export const SITES: Site[] = [
  {
    name: 'AFP',
    description: 'Agence FrancePresse',
    country: 'França',
    version: 'original',
    url: 'http://www.afp.com',
    enabled: true,
  },
  {
    name: 'Agerpres',
    description: 'Agenția Națională de Presă',
    country: 'Roménia',
    version: 'original',
    url: 'https://agerpres.ro/',
    enabled: true,
  },
  {
    name: 'Agerpres',
    description: 'Agenția Națională de Presă',
    country: 'Roménia',
    version: 'english',
    url: 'https://agerpres.ro/english',
    enabled: true,
  },
  {
    name: 'Albanian Telegraphic Agency',
    description: 'ATA/ATSH',
    country: 'Albânia',
    version: 'original',
    url: 'https://ata.gov.al/',
    enabled: true,
  },
  {
    name: 'Albanian Telegraphic Agency',
    description: 'ATA/ATSH',
    country: 'Albânia',
    version: 'english',
    url: 'https://en.ata.gov.al/',
    enabled: true,
  },
  {
    name: 'ANA',
    description: 'Agència de Notícies Andorrana',
    country: 'Andorra',
    version: 'original',
    url: 'https://www.ana.ad/',
    enabled: true,
  },
  {
    name: 'Anadolu Ajansi',
    description: 'Anadolu Agency',
    country: 'Turquia',
    version: 'original',
    url: 'https://www.aa.com.tr/',
    enabled: true,
  },
  {
    name: 'Anadolu Ajansi',
    description: 'Anadolu Agency',
    country: 'Turquia',
    version: 'english',
    url: 'https://www.aa.com.tr/en',
    enabled: true,
  },
  {
    name: 'ANAMPA / AMNA',
    description: 'AthensMacedonian News Agency',
    country: 'Grécia',
    version: 'original',
    url: 'https://www.amna.gr/',
    enabled: true,
  },
  {
    name: 'ANAMPA / AMNA',
    description: 'AthensMacedonian News Agency',
    country: 'Grécia',
    version: 'english',
    url: 'https://www.amna.gr/en',
    enabled: true,
  },
  {
    name: 'ANP',
    description: 'Algemeen Nederlands Persbureau',
    country: 'Países Baixos',
    version: 'original',
    url: 'https://www.anp.nl/',
    enabled: true,
  },
  {
    name: 'ANSA',
    description: 'Agenzia Nazionale Stampa Associata',
    country: 'Itália',
    version: 'original',
    url: 'https://www.ansa.it/',
    enabled: true,
  },
  {
    name: 'ANSA',
    description: 'Agenzia Nazionale Stampa Associata',
    country: 'Itália',
    version: 'english',
    url: 'https://www.ansa.it/english/',
    enabled: true,
  },
  {
    name: 'APA',
    description: 'Austria Press Agency',
    country: 'Áustria',
    version: 'original',
    url: 'https://apa.at/',
    enabled: true,
  },
  {
    name: 'AZERTAC',
    description: 'Azerbaijan State News Agency',
    country: 'Azerbeijão',
    version: 'original',
    url: 'https://azertag.az/',
    enabled: true,
  },
  {
    name: 'AZERTAC',
    description: 'Azerbaijan State News Agency',
    country: 'Azerbeijão',
    version: 'english',
    url: 'https://azertag.az/en/',
    enabled: true,
  },
  {
    name: 'Belga News Agency',
    description: null,
    country: 'Bélgica',
    version: 'original',
    url: 'https://www.belga.be/home/',
    enabled: true,
  },
  {
    name: 'BTA',
    description: 'Bulgarian News Agency',
    country: 'Bulgária',
    version: 'original',
    url: 'https://www.bta.bg/',
    enabled: true,
  },
  {
    name: 'BTA',
    description: 'Bulgarian News Agency',
    country: 'Bulgária',
    version: 'english',
    url: 'https://www.bta.bg/en',
    enabled: true,
  },
  {
    name: 'CNA',
    description: 'Cyprus News Agency',
    country: 'Chipre',
    version: 'english',
    url: 'https://www.cna.org.cy/',
    enabled: true,
  },
  {
    name: 'ČTK',
    description: 'Czech News Agency',
    country: 'República Checa',
    version: 'original',
    url: 'https://www.ctk.cz/',
    enabled: true,
  },
  {
    name: 'DPA',
    description: 'Deutsche PresseAgentur',
    country: 'Alemanha',
    version: 'original',
    url: 'https://www.dpa.com/',
    enabled: true,
  },
  {
    name: 'EFE',
    description: 'Agencia EFE',
    country: 'Espanha',
    version: 'original',
    url: 'https://efe.com/',
    enabled: true,
  },
  {
    name: 'EFE',
    description: 'Agencia EFE',
    country: 'Espanha',
    version: 'english',
    url: 'https://efe.com/en/',
    enabled: true,
  },
  {
    name: 'FENA',
    description: 'Federalna novinska agencija',
    country: 'Bósnia e Herzegovina',
    version: 'original',
    url: 'https://www.fena.ba/',
    enabled: true,
  },
  {
    name: 'FENA',
    description: 'Federalna novinska agencija',
    country: 'Bósnia e Herzegovina',
    version: 'english',
    url: 'https://www.fena.ba/category/32',
    enabled: true,
  },
  {
    name: 'HINA',
    description: 'Croatian News Agency',
    country: 'Croácia',
    version: 'original',
    url: 'https://www.hina.hr/',
    enabled: true,
  },
  {
    name: 'KeystoneSDA / KeystoneATS',
    description: 'Swiss Telegraphic Agency',
    country: 'Suíça',
    version: 'original',
    url: 'https://www.keystone-sda.ch/',
    enabled: true,
  },
  {
    name: 'KosovaPress',
    description: null,
    country: 'Kosovo',
    version: 'original',
    url: 'https://kosovapress.com/',
    enabled: true,
  },
  {
    name: 'KosovaPress',
    description: null,
    country: 'Kosovo',
    version: 'english',
    url: 'https://kosovapress.com/eng/',
    enabled: true,
  },
  {
    name: 'Latvijas nacionālā informācijas aģentūra',
    description: null,
    country: 'Letónia',
    version: 'original',
    url: 'https://leta.lv/',
    enabled: true,
  },
  {
    name: 'Lusa',
    description: 'Agência de Notícias',
    country: 'Portugal',
    version: 'original',
    url: 'https://www.lusa.pt/',
    enabled: true,
  },
  {
    name: 'Lusa',
    description: 'Agência de Notícias',
    country: 'Portugal',
    version: 'english',
    url: 'https://www.lusa.pt/lusanews',
    enabled: true,
  },
  {
    name: 'MTI',
    description: 'Magyar Távirati Iroda',
    country: 'Hungria',
    version: 'original',
    url: 'https://mti.hu/',
    enabled: true,
  },
  {
    name: 'NTB',
    description: 'Norwegian News Agency',
    country: 'Noruega',
    version: 'original',
    url: 'https://www.ntb.no/',
    enabled: true,
  },
  {
    name: 'PA Media:Press Association',
    description: null,
    country: 'Reino Unido',
    version: 'original',
    url: 'https://pa.media/',
    enabled: true,
  },
  {
    name: 'PAP',
    description: 'Polska Agencja Prasowa',
    country: 'Polónia',
    version: 'original',
    url: 'https://www.pap.pl/',
    enabled: true,
  },
  {
    name: 'PAP',
    description: 'Polska Agencja Prasowa',
    country: 'Polónia',
    version: 'english',
    url: 'https://www.pap.pl/en',
    enabled: true,
  },
  {
    name: 'Ritzaus Bureau',
    description: null,
    country: 'Dinamarca',
    version: 'original',
    url: 'https://ritzau.com/',
    enabled: true,
  },
  {
    name: 'STA',
    description: 'Slovenska Tiskovna Agencija',
    country: 'Eslovénia',
    version: 'original',
    url: 'https://www.sta.si/',
    enabled: true,
  },
  {
    name: 'STA',
    description: 'Slovenska Tiskovna Agencija',
    country: 'Eslovénia',
    version: 'english',
    url: 'https://english.sta.si/',
    enabled: true,
  },
  {
    name: 'STT',
    description: 'Finnish News Agency',
    country: 'Finlândia',
    version: 'original',
    url: 'https://stt.fi/',
    enabled: true,
  },
  {
    name: 'Tanjug',
    description: null,
    country: 'Sérvia',
    version: 'original',
    url: 'https://www.tanjug.rs/',
    enabled: true,
  },
  {
    name: 'Tanjug',
    description: null,
    country: 'Sérvia',
    version: 'english',
    url: 'https://www.tanjug.rs/english',
    enabled: true,
  },
  {
    name: 'TASR',
    description: 'Tlačová agentúra Slovenskej republiky',
    country: 'Eslováquia',
    version: 'original',
    url: 'https://www.tasr.sk/',
    enabled: true,
  },
  {
    name: 'TASR',
    description: 'Tlačová agentúra Slovenskej republiky',
    country: 'Eslováquia',
    version: 'english',
    url: 'https://www.tasr.sk/english',
    enabled: true,
  },
  {
    name: 'TASS',
    description: 'Russian News Agency TASS',
    country: 'Rússia',
    version: 'original',
    url: 'https://tass.com/',
    enabled: true,
  },
  {
    name: 'TASS',
    description: 'Russian News Agency TASS',
    country: 'Rússia',
    version: 'english',
    url: 'https://tass.ru/',
    enabled: true,
  },
  {
    name: 'TT',
    description: 'Tidningarnas Telegrambyrå / TT News Agency',
    country: 'Suécia',
    version: 'original',
    url: 'https://tt.se/',
    enabled: true,
  },
  {
    name: 'Ukrinform',
    description: 'National News Agency of Ukraine',
    country: 'Ucrânia',
    version: 'original',
    url: 'https://www.ukrinform.net/',
    enabled: true,
  },
  {
    name: 'Ukrinform',
    description: 'National News Agency of Ukraine',
    country: 'Ucrânia',
    version: 'english',
    url: 'https://www.ukrinform.ua/',
    enabled: true,
  },
] as const
